export const supportedLanguages = [
  { value: "en", label: "Global English", isDisabled: false },
  { value: "en_au", label: "Australian English", isDisabled: false },
  { value: "en_uk", label: "British English", isDisabled: false },
  { value: "en_us", label: "US English", isDisabled: false },
  { value: "es", label: "Spanish", isDisabled: false },
  { value: "fr", label: "French", isDisabled: false },
  { value: "de", label: "German", isDisabled: false },
  { value: "it", label: "Italian", isDisabled: false },
  { value: "pt", label: "Portuguese", isDisabled: false },
  { value: "nl", label: "Dutch", isDisabled: false },
  { value: "hi", label: "Hindi", isDisabled: false },
  { value: "ja", label: "Japanese", isDisabled: false },
  { value: "zh", label: "Chinese", isDisabled: false },
  { value: "fi", label: "Finnish", isDisabled: false },
  { value: "ko", label: "Korean", isDisabled: false },
  { value: "pl", label: "Polish", isDisabled: false },
  { value: "ru", label: "Russian", isDisabled: false },
  { value: "tr", label: "Turkish", isDisabled: false },
  { value: "uk", label: "Ukrainian", isDisabled: false },
  { value: "vi", label: "Vietnamese", isDisabled: false },
];
